name: PHP CI
on:
  push:
    branches:
      - main
      - dev

  pull_request:
    branches: [ dev ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  php:
    name: PHP 8.2

    runs-on: ubuntu-latest

    strategy:
      fail-fast: true

    steps:
      # Setup Github actions
      # https://github.com/actions/checkout (official)
      - name: Checkout
        uses: actions/checkout@v2

      # Setup PHP
      # https://github.com/shivammathur/setup-php (community)
      - name: Setup PHP, extensions and composer with shivammathur/setup-php
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          extensions: ctype, dom, filter, gd, iconv, intl, json, mbstring, pdo, pdo_mysql, xml
        env:
          update: true

      - name: Check PHP Version
        run: php -v

      # Install Composer
      - name: Get composer cache directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Cache composer dependencies
        uses: actions/cache@v1
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-

      # Install
      - name: Install
        run: ./entrypoint.sh install

      # Lint
      - name: Lint
        run: ./entrypoint.sh lint

      # Run Units Tests
      - name: Run Units Tests
        run: ./entrypoint.sh unit

